// Action types

export const SET_POLLS = "SET_POLLS";
export const ADD_POLL = "ADD_POLL";
export const SHOW_ADD_POLL_MODAL = "SHOW_ADD_POLL_MODAL";
export const SHOW_ADD_POLL_SUCCESS_MODAL = "SHOW_ADD_POLL_SUCCESS_MODAL";
export const SHOW_ADD_POLL_FAILURE_MODAL = "SHOW_ADD_POLL_FAILURE_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";